eslint ts jest 추가
aptakqmf12/twdash pull request #2
Opened 2023-02-19 06:55 UTC by aptakqmf12

2023-02-19 14:20 UTC, dogyeong requested changes

2023-02-19 14:20 UTC, dogyeong commented on .eslintrc.js
> +  extends: ['airbnb-base', 'eslint:recommended', 'plugin:@typescript-eslint/recommended'],
prettier 설정이 안돼있네요

2023-02-19 14:20 UTC, dogyeong commented on .eslintrc.js
> +  },
- `eslint-plugin-import` 룰 설정이 제대로 안돼있어서 import에서 에러가 나는거같네요
- 일단 [eslint-config-airbnb-typescript](https://www.npmjs.com/package/eslint-config-airbnb-typescript) 요걸 한번 적용해보세요
- 그리고, jest plugin도 추가해보세요

2023-02-19 14:20 UTC, dogyeong commented on babel.config.js
> +};
babel 설정은 왜 있나요?

2023-02-19 14:20 UTC, dogyeong commented on jest.config.ts
> +export default config;
저는 로컬에서 테스트가 안돌아가네요. 설정이 잘못돼있는 것 같아요
<img width="911" alt="image" src="https://user-images.githubusercontent.com/40662323/219953600-32f587b0-1ec1-4681-a9b2-d27329c2e72c.png">

2023-02-19 14:20 UTC, dogyeong commented on package.json
> +    "@babel/preset-typescript": "^7.18.6",
babel은 쓰는 건지 모르겠네요. 안쓰는 거면 제거하는 게 좋겠습니다

2023-02-19 14:20 UTC, dogyeong commented on package.json
> +    "typescript": "^4.9.5"
typescript는 왜 devDependency가 아닌가요?

2023-02-19 14:20 UTC, dogyeong commented on dist/main.js
> +//# sourceMappingURL=main.js.map
dist 폴더는 제외해주세요~

2023-02-19 14:20 UTC, dogyeong commented on tsconfig.json
> +    "module": "system",
왜 module: system인가요?

2023-02-20 15:28 UTC, aptakqmf12 commented on babel.config.js
> +};
jest에서 import를 쓰려면 babel을 설정해줘야한다는 내용을 봐서 추가했는데
해도 안되는..

2023-02-20 15:31 UTC, aptakqmf12 commented on babel.config.js
> +};
https://velog.io/@okyungjin/Jest-Cannot-use-import-statement-outside-a-module-%EC%98%A4%EB%A5%98-%ED%95%B4%EA%B2%B0

2023-02-20 16:46 UTC, dogyeong requested changes

2023-02-20 16:46 UTC, dogyeong commented on .eslintrc.js
> +};
지금 eslint 설정에 에러가 있어서 아예 안돌고 있어요.
- prettier가 plugin으로 지정돼있는데, eslint-plugin-prettier가 추가돼있지 않음
- airbnb-typescript/base 설정이 다 안돼있음. [여기](https://www.npmjs.com/package/eslint-config-airbnb-typescript) 참고해주세요
- jest 플러그인은 override옵션을 활용해서 테스트 파일에만 적용되게 해주세요
- rules 옵션은 다 지워주세요 (설정 제대로 되면 필요없을 것 같네요)

2023-02-25 13:10 UTC, closed without merging